import MainHeader from '@/components/main-header/MainHeader'
import './globals.css'
import { Inter } from 'next/font/google'
import MainFooter from '@/components/main-footer/MainFooter'
import BannerFijo from '@/components/banner-fijo/BannerFijo'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <main className="app">
          <MainHeader />
          <BannerFijo />
          {children}
          <MainFooter />
        </main>
      </body>
    </html>
  )
}
